### ISSUE TITLE
Questions regarding the signaling server

### ISSUE THREAD

**Issue by janhelwich** [freshtilledsoil/webrtc-jquery-plugin#1]
Hi,

first of all: awesome work. thx a lot.

We'd like to use the plugin for our music-e-learning-platform. You have hardcoded the signaling server of your company in the JS code. 
So my questions are: 
Is it ok to use it?
Have you used/written an open source impl of the server, which we can use and host ourself?

Thanks in advance and best regards
Jan

**Comment by songchaofly** [comment]
"Have you used/written an open source impl of the server, which we can use and host ourself?"

I have the same question.

Thanks in advance and best regards.
Anthony Song

**Comment by janhelwich** [comment]
sry. no. 

we use opentok right now. it is still free for P2P, allthough this will definitly change.

regards
jan

**Comment by ksrichard** [comment]
can you post here or in e-mail to me the code for the server?

**Comment by janhelwich** [comment]
as said, we don't use a server for this anymore. opentok is a tool by tokbox. just google it.

**Comment by haslinger** [comment]
First: Awesome work, congratulations!

Same question here:  Which signalling server is used?
Is there a way to install it on my server?

**Comment by timwright12** [comment]
Hey folks, You should feel free to use the signaling server in the plugin if you'd like, beyond that we don't have much information. Thanks for using the plugin, if someone wants to fork it and add the server code I'll link it up in the readme!
