### ISSUE TITLE
Not working in Firefox any more

### ISSUE THREAD

**Issue by haslinger** [freshtilledsoil/webrtc-jquery-plugin#11]
I see, there was an issue submitted without an example. 
Here is the example working in Chrome, but not in Firefox (34.0 on Ubuntu Linux): http://www.informatom.com/videochat
Sorry, texts are in German, just click on the button "Videochat starten".

Debug log in Firefox says:

```
Attempting to connect to local media (video/audio)
allow status
An error occured: [CODE undefined]
```

I am sure, that it worked on earlier versions of Firefox with the same .js-File.
If you need any more input, please tell me.

**Comment by poiuty** [comment]
Try 
n.GetUserMedia = (n.getUserMedia || n.webkitGetUserMedia || n.mozGetUserMedia || n.msGetUserMedia);

**Comment by haslinger** [comment]
Yes, that's a fix.
