### ISSUE TITLE
Wont work on https protected websites?

### ISSUE THREAD

**Issue by khabaal** [freshtilledsoil/webrtc-jquery-plugin#2]
Well, the title says it all. I tried to add your script to an encrypted website and it just stops after "Please click 'Share Selected Devices' to start local video/audio stream".

I did share the devices but nothing. It works flawlessly on http sites.

**Comment by seang96** [comment]
I tried 1.0.6 on http and I experienced the same problem.

**Comment by timwright12** [comment]
Do you have an example? It may be how the plugin is being linked
