### ISSUE TITLE
Ipad?

### ISSUE THREAD

**Issue by LaraCan** [freshtilledsoil/webrtc-jquery-plugin#3]
Hi, 
I've tried using the plugin on the ipad - using Chrome - and it doesn't work, the screen turns black. Any chance of a fix?

**Comment by onepaul** [comment]
Hi & thank you for your message!  For the time being, there is a 'silent' codec war of sorts going on that is currently being tackled by the W3C's Internet Engineering Task Force (IETF).  While there is high optimism that this disagreement in mandatory codec will be resolved soon, I'm sad to say that in the meantime WebRTC (at least in a web browser on an iOS device) will not be available.  Though there are open source options that you can find, via an internet search, to make it work on an iPad within a native app.  See this article for the latest update: https://aragonresearch.com/webrtc-update-still-no-consensus-on-a-mti-video-codec/

**Comment by LaraCan** [comment]
Gotcha, thanks very much!
