### ISSUE TITLE
I have problem with voice.

### ISSUE THREAD

**Issue by mikpetr** [freshtilledsoil/webrtc-jquery-plugin#4]
Hi. I have problem with voice. I hearing my voice during chat.

**Comment by onepaul** [comment]
Hi.  We've encountered similar when testing two devices closely or when in a a video chat session with someone and the volume turned all the way up, causing our microphone to easily pick up what we hear on the other end (this causes a feedback loop echo effect or in rare cases a ringing sound).

Ultimately, we've been able to eliminate this feedback loop by wearing a headset while in a video chat session.  If this does not alleviate the issue please let us know.

Best,

Paul
