### ISSUE TITLE
How to change the "signallingServer"

### ISSUE THREAD

**Issue by ndeztea** [freshtilledsoil/webrtc-jquery-plugin#5]
Hi,

Thank you very much for very great plugins, I really like it for my great projects ;)

I just have one question, is it possible to change the "signallingServer" to our server instead? what should I do, can you provide me some steps to achive that?

thank you

**Comment by ndeztea** [comment]
If I need to buy and install it on my server, how is it much? please let me know..

**Comment by sendtoharmeet** [comment]
Please tell how to change signalling server ?

**Comment by haslinger** [comment]
Same question here: Which signalling server is used?
Is there a way to install it on my server?

**Comment by timwright12** [comment]
The signalling server can be changed in the "settings" object. You can see it much easier in the unminified version of the plugin. We're not currently providing support for setting up your own signalling server.
