### ISSUE TITLE
Peer found, establishing connection...

### ISSUE THREAD

**Issue by zeusgrs** [freshtilledsoil/webrtc-jquery-plugin#8]
when two people are connected to the page displays the following message and halts there
"Peer found, establishing connection..."
download code from here and simple run in my apache server

need open some ports in firewall? or need run some other services?

thank you

**Comment by Chirag2411** [comment]
I'm having the same issue.

**Comment by timwright12** [comment]
Do you have a live example of this? Could be a server hiccup

**Comment by timwright12** [comment]
Toss a link in here if you don't mind

**Comment by balazshuszar** [comment]
still not working in my Apache, not even when try to establish connection via your embedded application on your home page: http://www.freshtilledsoil.com/the-future-of-web/webrtc-video/
"Peer found, establishing connection" forever...
