### ISSUE TITLE
Audio Feedback on local viewer

### ISSUE THREAD

**Issue by simonhead666** [freshtilledsoil/webrtc-jquery-plugin#9]
Every time I load the page, the local view window needs to be muted..  other wise, there is wailing feedback on my laptop.
 I couldn't find the fix.. any help would be awesome!!

**Comment by timwright12** [comment]
That's probably the sound from your speakers cycling back into the microphone causing feedback. Try using a headset.

**Comment by simonhead666** [comment]
I fixed it by changing the video div in the index HTML file to audio = "muted". Audio is still received at the remote end and there is no silly echo.

**Comment by jonasmped** [comment]
Hi Simon
This fix is not working for me. Added audio="muted" to my local video but it did not fix the issue.
<video id="localVideo" class="local-video" audio="muted"></video>
Can you help me out please?
Jonas

**Comment by simonhead666** [comment]
hi
here's the link to my index.html
https://www.dropbox.com/s/i93mm7tuvc6x90m/index.html?dl=0

or check the image
![screen shot 2015-03-05 at 10 21 06 am](https://cloud.githubusercontent.com/assets/6092713/6507641/66af9250-c321-11e4-926b-1c64189c205c.png)
